# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'
target 'MVVM-C' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-C
  pod 'RxSwift', '4.3.1'
  pod 'RxCocoa', '4.3.1'

end
